config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    path('', include('movies.urls')),
    path('', include('pages.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

urlpatterns = [
    path('login/', views.TelegramLoginView.as_view(), name='telegram_login'),
    path('login/handler/', views.TelegramLoginHandlerView.as_view(), name='telegram_login_handler'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('select_movies/', views.SelectMoviesView.as_view(), name='select_movies'),
    path('watched_movies/', views.WatchedMoviesView.as_view(), name='watched_movies'),
    path('rank_movies/', views.RankMoviesView.as_view(), name='rank_movies'),
    path('top_movies/', views.TopRankingsView.as_view(), name='top_movies'),
    path('user/<uuid:uuid>/', views.PublicTopRankingsView.as_view(), name='public_top_movies'),
    path('discover_movies/', views.DiscoverMovies.as_view(), name='discover_movies'),
    path('see/<int:movie_id>', views.see, name='see'),
    path('unsee/<int:movie_id>', views.unsee, name='unsee'),
    path('api/seen/<int:movie_id>', views.seen_api, name='seen_api'),
    path('api/notseen/<int:movie_id>', views.notseen_api, name='notseen_api'),
    path('compare/<int:main_movie_id>/<int:other_movie_id>/<int:is_main_movie_better>', views.compare, name='compare'),
]

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView, BroadcastPageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('broadcast/', BroadcastPageView.as_view(), name='broadcast'),
]

movies/models.py
from pyexpat import model
from django.db import models

from accounts.models import CustomUser

class Movie(models.Model):
    title = models.CharField(max_length=255)
    year = models.IntegerField()
    # poster = models.ImageField(upload_to='posters/')
    poster = models.URLField()

    def __str__(self):
        return self.title

class Director(models.Model):
    name = models.CharField(max_length=255)
    movies = models.ManyToManyField(Movie, null=True, blank=True)

    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=255)
    movies = models.ManyToManyField(Movie, null=True, blank=True)

    def __str__(self):
        return self.name

def get_smallest_movie_id_by_user(user):
    return MovieSeen.objects.filter(user=user).aggregate(models.Min('movie_id'))['movie_id__min']    

class MovieSeen(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    last_checked_movie_index = models.IntegerField(blank=True)

    class Meta:
        index_together = [
            ['user', 'movie'],
        ]

    def __str__(self):
        return self.movie.title
    
    def save(self, **kwargs):
        if not self.pk:
            self.last_checked_movie_index = get_smallest_movie_id_by_user(self.user) or 0
        return super().save(**kwargs)

class MovieComparision(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    better_movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='better_movie')
    worse_movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='worse_movie')
    
    class Meta:
        unique_together = [
            ['user', 'better_movie', 'worse_movie']
        ]

    def __str__(self):
        return f'{self.better_movie.title} > {self.worse_movie.title}'

class MovieNotSeen(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = [
            ['user', 'movie']
        ]

    def __str__(self):
        return f'{self.user.username} - {self.movie.title}'

movies/views.py
from re import template
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from typing import Any, Dict
from itertools import permutations
from random_username.generate import generate_username
import requests
import random
import botogram

from . import models
from .authentication import verify_auth
import movies
# Create your views here.

telegram_bot = botogram.create(settings.TELEGRAM_BOT_TOKEN)

class TelegramLoginView(generic.TemplateView):
    template_name = 'movies/telegram_login.html'
    
class TelegramLoginHandlerView(generic.View):
    def get(self, request, *args, **kwargs):
        data = request.GET
        token = settings.TELEGRAM_BOT_TOKEN
        if verify_auth(data, token):
            user, created = models.CustomUser.objects.get_or_create(
                telegram_id=data['id'],
                defaults={
                    'username': data.get('username', generate_username()),
                    'first_name': data.get('first_name', ''),
                    'last_name': data.get('last_name', ''),
                }
            )
            if created:
                telegram_bot.chat(data['id']).send(
                    f'Welcome to the movies bot, {user.username}!\n'
                    'You can now use the web interface to rank movies you have seen.'
                )
                telegram_bot.chat(settings.TELEGRAM_ADMIN_ID).send(
                    f'New user @{user.username} - {user.first_name} {user.last_name} - {user.telegram_id} registered.'
                )
            login(request, user)
            return redirect(reverse_lazy('home'))
        return redirect(reverse_lazy('telegram_login'))

class SelectMoviesView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'movies/select_movies.html'

    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        if not query:
            return redirect(reverse_lazy('home'))
        
        # genre = request.GET.get('genre')
        year = request.GET.get('year')
        try:
            API_URL = f"http://www.omdbapi.com/?apikey=b38a0c33&s={query}"  
        except:
            # Internal server error, notify user
            return redirect(reverse_lazy('home'))
        resp = requests.get(API_URL)
        data = resp.json()
        for row in data.get('Search', []):
            print(row)
            try:
                try:
                    row_year = int(row['Year'].split('–')[0])
                except:
                    row_year = 0

                new_movie = models.Movie.objects.get_or_create(
                    title=row['Title'],
                    year=row_year,
                    poster=row['Poster'],
                )
                if new_movie[0].poster == 'N/A':
                    resp = requests.get(f"http://www.omdbapi.com/?apikey=b38a0c33&t={row['Title']}")
                    data = resp.json()
                    new_movie[0].poster = data['Poster']
                    new_movie[0].save()

            except Exception as e:
                print(e)
                pass
        
        movies = models.Movie.objects.filter(title__icontains=query)
        print("MOVIES:", movies)
        if year:
            kwargs['selected_year'] = year
            movies = movies.filter(year=year)

        seen_movies = models.MovieSeen.objects.filter(user=request.user).values_list('movie_id', flat=True)
        for movie in movies:
            if movie.id in seen_movies:
                movie.is_seen = True
            else:
                movie.is_seen = False

        kwargs['movies'] = movies
        kwargs['q'] = query
        kwargs['years'] = map(str, movies.values_list('year', flat=True).distinct())
        # kwargs['genres'] = models.Genre.objects.all()
        return super().get(request, *args, **kwargs)

class WatchedMoviesView(LoginRequiredMixin, generic.ListView):
    template_name = 'movies/watched_movies.html'
    paginate_by = 9

    def get_queryset(self):
        return list(map(lambda movieseen: movieseen.movie, models.MovieSeen.objects.filter(user=self.request.user)))

class RankMoviesView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'movies/rank_movies.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        seen_movies = models.MovieSeen.objects.filter(user=self.request.user).prefetch_related('movie')
        shuffled_seen_movies = list(seen_movies)
        random.shuffle(shuffled_seen_movies)
        for movie in shuffled_seen_movies:
            remaining_seen_movies = models.MovieSeen.objects.filter(user=self.request.user).filter(
                Q(id__lt=movie.id) & Q(id__gt=movie.last_checked_movie_index)).order_by('id')
            if remaining_seen_movies:
                kwargs['movies'] = [movie.movie, remaining_seen_movies[0].movie]
                break
        return super().get_context_data(**kwargs)
    
class TopRankingsView(LoginRequiredMixin, generic.ListView):
    template_name = 'movies/top_rankings.html'
    paginate_by = 10
    
    def get_queryset(self):
        return list(map(lambda movieseen: movieseen.movie, models.MovieSeen.objects.filter(user=self.request.user).order_by('-score')))

class PublicTopRankingsView(generic.ListView):
    template_name = 'movies/public_top_rankings.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        uuid = self.kwargs['uuid']
        kwargs["user_name"] = models.CustomUser.objects.get(public_url_uuid=uuid)
        return super().get_context_data(**kwargs)
    
    def get_queryset(self):
        uuid = self.kwargs['uuid']
        user = models.CustomUser.objects.get(public_url_uuid=uuid)
        return list(map(lambda movieseen: movieseen.movie, models.MovieSeen.objects.filter(user=user).order_by('-score')))


@login_required
def see(request, movie_id):
    movie = models.Movie.objects.get(id=movie_id)
    models.MovieSeen.objects.get_or_create(user=request.user, movie=movie)
    try:
        return redirect(request.META.get('HTTP_REFERER'))
    except:
        return redirect(reverse_lazy('home'))

@login_required
def unsee(request, movie_id):
    movie = models.Movie.objects.get(id=movie_id)
    models.MovieSeen.objects.filter(user=request.user, movie=movie).delete()
    return redirect(reverse_lazy('watched_movies'))

@login_required
def compare(request, main_movie_id, other_movie_id, is_main_movie_better):
    main_movie_seen = models.MovieSeen.objects.get(user=request.user, movie__id=main_movie_id)
    other_movie_seen = models.MovieSeen.objects.get(user=request.user, movie__id=other_movie_id)
    if is_main_movie_better:
        main_movie_seen.score += 1
        other_movie_seen.score -= 1
    else:
        main_movie_seen.score -= 1
        other_movie_seen.score += 1
    main_movie_seen.last_checked_movie_index = other_movie_seen.id
    main_movie_seen.save()
    other_movie_seen.save()
    return redirect(reverse_lazy('rank_movies'))

class DiscoverMovies(LoginRequiredMixin, generic.ListView):
    template_name = 'movies/discover_movies.html'
    
    def get_queryset(self):
        # all movies with at least one seen
        seen_movies = models.MovieSeen.objects.values_list('movie_id', flat=True)
        all_movies = models.Movie.objects.filter(id__in=seen_movies)
        return all_movies.exclude(Q(id__in=models.MovieSeen.objects.filter(user=self.request.user).values_list('movie_id', flat=True))|Q(id__in=models.MovieNotSeen.objects.filter(user=self.request.user).values_list('movie_id', flat=True)))

@login_required
def seen_api(request, movie_id):
    movie = models.Movie.objects.get(id=movie_id)
    models.MovieSeen.objects.get_or_create(user=request.user, movie=movie)
    return JsonResponse({'success': True})

@login_required
def notseen_api(request, movie_id):
    movie = models.Movie.objects.get(id=movie_id)
    models.MovieNotSeen.objects.get_or_create(user=request.user, movie=movie)
    return JsonResponse({'success': True})

templates/movies/discover_movies.html
{% extends '_base.html' %}

{% block title %}Discover Movies{% endblock %}

{% block content %}

<style>

    #board {
        width: 100%;
        height: 100%;
        min-height: 100%;
        /* position: relative; */
        /* overflow: hidden; */
        background-color: rgb(245, 247, 250);
    }

    .card {
        width: 320px;
        
        position: absolute;
        top: 50%;
        left: 50%;
        border-radius: 1%;
        box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.1);
        background-color: white;
        transform: translateX(-50%) translateY(-50%) scale(0.95);
    }
</style>
</head>

<body>
    <div id="board">
        
    </div>
    <!-- small alert box at the bottom of screen -->
    {% if not object_list %}
        <div class="alert alert-info text-center">
            <small>Search for other movies on the search bar above.</small>
            
        </div>
    {% else %}
        <div class="alert alert-warning text-center">
            <small>This is an experimental feature. Please use with caution.</small>
            <p>Swipe right on a movie to mark is as seen. Swipe left to mark it as not seen.</p>
        </div>
    {% endif %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>
    <script>
        /* LikeCarousel (c) 2019 Simone P.M. github.com/simonepm - Licensed MIT */

        class Carousel {

            constructor(element) {

                this.board = element

                // handle gestures
                this.handle()

            }

            handle() {

                // list all cards
                this.cards = this.board.querySelectorAll('.card')

                // get top card
                this.topCard = this.cards[this.cards.length - 1]

                // get next card
                this.nextCard = this.cards[this.cards.length - 2]

                // if at least one card is present
                if (this.cards.length > 0) {

                    // set default top card position and scale
                    this.topCard.style.transform =
                        'translateX(-50%) translateY(-50%) rotate(0deg) rotateY(0deg) scale(1)'

                    // destroy previous Hammer instance, if present
                    if (this.hammer) this.hammer.destroy()

                    // listen for tap and pan gestures on top card
                    this.hammer = new Hammer(this.topCard)
                    this.hammer.add(new Hammer.Tap())
                    this.hammer.add(new Hammer.Pan({
                        position: Hammer.position_ALL,
                        threshold: 0
                    }))

                    // pass events data to custom callbacks
                    this.hammer.on('tap', (e) => {
                        this.onTap(e)
                    })
                    this.hammer.on('pan', (e) => {
                        this.onPan(e)
                    })

                }

            }

            onTap(e) {

                // get finger position on top card
                let propX = (e.center.x - e.target.getBoundingClientRect().left) / e.target.clientWidth

                // get rotation degrees around Y axis (+/- 15) based on finger position
                let rotateY = 15 * (propX < 0.05 ? -1 : 1)

                // enable transform transition
                this.topCard.style.transition = 'transform 100ms ease-out'

                // apply rotation around Y axis
                this.topCard.style.transform =
                    'translateX(-50%) translateY(-50%) rotate(0deg) rotateY(' + rotateY + 'deg) scale(1)'

                // wait for transition end
                setTimeout(() => {
                    // reset transform properties
                    this.topCard.style.transform =
                        'translateX(-50%) translateY(-50%) rotate(0deg) rotateY(0deg) scale(1)'
                }, 100)

            }

            onPan(e) {

                if (!this.isPanning) {

                    this.isPanning = true

                    // remove transition properties
                    this.topCard.style.transition = null
                    if (this.nextCard) this.nextCard.style.transition = null

                    // get top card coordinates in pixels
                    let style = window.getComputedStyle(this.topCard)
                    let mx = style.transform.match(/^matrix\((.+)\)$/)
                    this.startPosX = mx ? parseFloat(mx[1].split(', ')[4]) : 0
                    this.startPosY = mx ? parseFloat(mx[1].split(', ')[5]) : 0

                    // get top card bounds
                    let bounds = this.topCard.getBoundingClientRect()

                    // get finger position on top card, top (1) or bottom (-1)
                    this.isDraggingFrom =
                        (e.center.y - bounds.top) > this.topCard.clientHeight / 2 ? -1 : 1

                }

                // get new coordinates
                let posX = e.deltaX + this.startPosX
                let posY = e.deltaY + this.startPosY

                // get ratio between swiped pixels and the axes
                let propX = e.deltaX / this.board.clientWidth
                let propY = e.deltaY / this.board.clientHeight

                // get swipe direction, left (-1) or right (1)
                let dirX = e.deltaX < 0 ? -1 : 1

                // get degrees of rotation, between 0 and +/- 45
                let deg = this.isDraggingFrom * dirX * Math.abs(propX) * 45

                // get scale ratio, between .95 and 1
                let scale = (95 + (5 * Math.abs(propX))) / 100

                // move and rotate top card
                this.topCard.style.transform =
                    'translateX(' + posX + 'px) translateY(' + posY + 'px) rotate(' + deg + 'deg) rotateY(0deg) scale(1)'

                // scale up next card
                if (this.nextCard) this.nextCard.style.transform =
                    'translateX(-50%) translateY(-50%) rotate(0deg) rotateY(0deg) scale(' + scale + ')'

                if (e.isFinal) {

                    this.isPanning = false

                    let successful = false

                    // set back transition properties
                    this.topCard.style.transition = 'transform 200ms ease-out'
                    if (this.nextCard) this.nextCard.style.transition = 'transform 100ms linear'

                    // check threshold and movement direction
                    if (propX > 0.25 && e.direction == Hammer.DIRECTION_RIGHT) {

                        successful = true
                        // get right border position
                        posX = this.board.clientWidth

                    } else if (propX < -0.25 && e.direction == Hammer.DIRECTION_LEFT) {

                        successful = true
                        // get left border position
                        posX = -(this.board.clientWidth + this.topCard.clientWidth)

                    } else if (propY < -0.25 && e.direction == Hammer.DIRECTION_UP) {

                        successful = true
                        // get top border position
                        posY = -(this.board.clientHeight + this.topCard.clientHeight)

                    }

                    if (successful) {

                        // throw card in the chosen direction
                        this.topCard.style.transform =
                            'translateX(' + posX + 'px) translateY(' + posY + 'px) rotate(' + deg + 'deg)'
                        

                        let direction = dirX == 1 ? 'right' : 'left'
                        
                        if(direction == 'right'){
                            left_swiped(this.topCard.getAttribute('data-id'))
                        }
                        else{
                            right_swiped(this.topCard.getAttribute('data-id'))
                        }
                        // remove top card
                        setTimeout(() => {
                            this.topCard.parentNode.removeChild(this.topCard)
                            this.handle()
                        }, 200);

                    } else {

                        // reset cards position and size
                        this.topCard.style.transform =
                            'translateX(-50%) translateY(-50%) rotate(0deg) rotateY(0deg) scale(1)'
                        if (this.nextCard) this.nextCard.style.transform =
                            'translateX(-50%) translateY(-50%) rotate(0deg) rotateY(0deg) scale(0.95)'

                    }

                }

            }

            push(id, name, image, year) {

                let name_div = document.createElement('h5')
                name_div.innerHTML = name
                name_div.classList.add('card-title')
                name_div.classList.add('text-center')

                let image_div = document.createElement('div')
                image_div.className = 'image'
                image_div.style.backgroundImage = 'url(' + image + ')'
                image_div.style.height = '400px'
                
                let year_div = document.createElement('div')
                year_div.className = 'year'
                year_div.classList.add('text-center')
                year_div.innerHTML = `Released in ${year}`

                let br = document.createElement('br')
                
                let card_body = document.createElement('div')
                card_body.className = 'card-body'
                card_body.appendChild(name_div)
                card_body.appendChild(image_div)
                card_body.appendChild(year_div)
                card_body.appendChild(br)

                
                let card = document.createElement('div')

                card.classList.add('card')
                card.setAttribute('data-id', id)
                
                card.appendChild(card_body)

                this.board.insertBefore(card, this.board.firstChild)
                this.handle()
            }

        }

        let board = document.querySelector('#board')

        let carousel = new Carousel(board)
        {% for obj in object_list %}
            carousel.push('{{ obj.id }}', '{{ obj.title }}', '{{ obj.poster }}', '{{ obj.year }}')
        {% endfor %}
        carousel.handle()
        
        function left_swiped(id){
            console.log("Swiped left: " + id)
            // call api/seen/{id} 
            fetch('/api/seen/' + id, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
        }
        function right_swiped(id){
            console.log("Swiped right: " + id)
            // call api/notseen/{id}
            fetch('/api/notseen/' + id, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json'
                }
            })
        }
        
        </script>
        
        
{% endblock content %}

templates/movies/public_top_rankings.html
{% extends '_base.html' %}

{% block title %}Top Movies For user {{user}} {% endblock %}

{% block content %}

<!-- A top 10 ranking list of movies with rank, title: score, image, genres and year -->
<!-- each row has one card -->
<h3 class="text-center">Top Movies For user {{user_name}}</h3>
<div>
    <!-- center cards -->
    {% for movie in page_obj %}
    <div class="row">

        <div class="col-md-3"></div>
        <div class="card col-md-6">
            <div class="card-title">
                <span class="col-sm-6text-left">
                    <span>
                        <h4>
                            Rank: {{ forloop.counter0|add:page_obj.start_index }}
                            <span class="float-right">
                                <span class="badge badge-secondary text-right">{{ movie.score }}</span>
                            </span>
                        </h4>
                    </span>
                    <!-- add right aligned score -->
                </span>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center">{{ movie.title }}</h5>
                <!-- <div class="text-center">
                    Genres: 
                    {% for genre in movie.genre_set.all %}
                    {{ genre.name }}
                    {% endfor %}
                </div> -->
                <img src="{{ movie.poster }}" class="img-thumbnail img-fluid card-img-top">
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
    {% endfor %}
    {% if page_obj|length > 0 %}
    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'top_movies' %}?page={{ page_obj.previous_page_number }}"
                            aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}
                    {% for page in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                        <a class="page-link" href="{% url 'top_movies' %}?page={{ page }}">{{ page }}</a>
                    </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'top_movies' %}?page={{ page_obj.next_page_number }}"
                            aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
    {%else%}
    <div class="row">
        <div class="col-md-12">
            <h4 class="text-center alert alert-info">No movies ranked by user yet.</h4>
        </div>
    </div>
    {% endif %}

</div>

{% endblock content %}

templates/movies/telegram_login.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Log in{% endblock %}

{% block content %}
<h2>Log in</h2>
<script async src="https://telegram.org/js/telegram-widget.js?15" data-telegram-login="two_k_bot" data-size="large"
    data-auth-url="http://toppicks.proto-code.com{% url 'telegram_login_handler' %}" data-request-access="write"></script>
    
{% endblock content %}

templates/movies/top_rankings.html
{% extends '_base.html' %}

{% block title %}Top Movies{% endblock %}

{% block content %}

<!-- A top 10 ranking list of movies with rank, title: score, image, genres and year -->
<!-- each row has one card -->
<h3>Top Movies</h3>
<div >   
    <!-- center cards -->
    {% for movie in page_obj %}
    <div class="row">

        <div class="col-md-3"></div>
        <div class="card col-md-6">
            <div class="card-title">
                <span class="col-sm-6text-left">
                    <span>
                        <h4>
                            Rank: {{ forloop.counter0|add:page_obj.start_index }}
                            <span class="float-right">
                                <span class="badge badge-secondary text-right">{{ movie.score }}</span>
                            </span> 
                        </h4>
                    </span>
                    <!-- add right aligned score -->
                </span>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center">{{ movie.title }}</h5>
                <!-- <div class="text-center">
                    Genres: 
                    {% for genre in movie.genre_set.all %}
                    {{ genre.name }}
                    {% endfor %}
                </div> -->
                <img src="{{ movie.poster }}" class="img-thumbnail img-fluid card-img-top">
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
    {% endfor %}
    <!-- pagination -->
    <div class="row">
        <div class="col-md-12">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'top_movies' %}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}
                    {% for page in page_obj.paginator.page_range %}
                    <li class="page-item {% if page_obj.number == page %} active {% endif %}">
                        <a class="page-link" href="{% url 'top_movies' %}?page={{ page }}">{{ page }}</a>
                    </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="{% url 'top_movies' %}?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>

{% endblock content %}